apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: repo-359
  annotations:
    github.com/project-slug: portal-demo-large-org/repo-359
spec:
  type: website
  lifecycle: experimental
  owner: portal
